server:
  port: 8080
  servlet:
    context-path: /congty

spring:
  application:
    name: congty
  datasource:
    url: "jdbc:mysql://localhost:3306/congty"
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: validate # hoáº·c none
    show-sql: true